services:
  db:
    image: mysql:latest
    platform: linux/amd64
    environment:
      TZ: Asia/Tokyo
      MYSQL_DATABASE: 'ebichu_map'
      MYSQL_USER: 'ebichu'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root_password'
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'

  web:
    build: .
    command: rails new . --force --database=mysql --skip-bundle
    ports:
      - "3000:3000"
    environment:
      - TZ=Asia/Tokyo
    depends_on:
      - db
volumes:
  mysql_data:
  bundle_data:
  node_modules:
