version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'ebichu_map'
      MYSQL_USER: 'ebichu'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root_password'
    ports:
      - '3306:3306'

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    depends_on:
      - db
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: 'mysql2://ebichu:password@db:3306/ebichu_map'

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - '8080:8080'
    environment:
      REACT_APP_API_URL: 'http://localhost:3000'
      